"""Source phrase -> atomic skills, for the `other` bucket of new-skills categorization.

Compound JD phrases are split into individual skills so each one is listed once.
Product names keep conventional casing; generic practices are lowercase.
Unmapped phrases pass through unchanged and are reported by the generator.
"""

ATOMS = {
    "A/B testing and conversion rate optimisation": ["A/B testing", "conversion rate optimization"],
    "A/B testing and experimental design": ["A/B testing", "experimental design"],
    "Accessibility standards (WCAG, ARIA)": ["accessibility standards", "WCAG", "ARIA"],
    "Advanced spreadsheet modelling (Excel or Google Sheets)": ["spreadsheet modeling", "Excel", "Google Sheets"],
    "Agile / Scrum": ["Agile / Scrum"],
    "Agile / SCRUM ceremonies": ["Agile / Scrum", "agile ceremonies"],
    "Agile ceremonies (sprint planning, standups, retrospectives)": ["agile ceremonies", "sprint planning", "standups", "retrospectives"],
    "Agile delivery": ["Agile / Scrum"],
    "Agile methodologies (named)": ["Agile / Scrum"],
    "Agile Scrum delivery": ["Agile / Scrum"],
    "Agile, sprint planning, standups, retrospectives (named methodology, see gaps file)": ["Agile / Scrum", "sprint planning", "standups", "retrospectives"],
    "Airflow": ["Apache Airflow"],
    "Alerting and health monitoring platforms": ["alerting", "health monitoring"],
    "Analytic Development Life Cycle": ["analytic development life cycle"],
    "Angular 14 (specific version)": ["Angular"],
    "Apache Kafka": ["Apache Kafka"],
    "Apache Parquet and Apache Iceberg": ["Apache Parquet", "Apache Iceberg"],
    "Apache Spark or distributed processing": ["Apache Spark", "distributed data processing"],
    "API rate limiting and backoff against throttled upstreams": ["API rate limiting", "retry and backoff handling"],
    "Architectural design reviews": ["architecture design review"],
    "Architecture and design artifacts": ["architecture documentation"],
    "ArgoCD and GitOps deployment": ["ArgoCD", "GitOps"],
    "Artifactory / Nexus": ["Artifactory", "Nexus"],
    "Aurora PostgreSQL": ["Amazon Aurora PostgreSQL"],
    "Automated data quality monitoring and anomaly flagging": ["data quality monitoring", "anomaly detection"],
    "Automated visualization": ["automated visualization"],
    "AWS Athena and S3-backed analytics": ["AWS Athena", "Amazon S3"],
    "AWS CLI and SAM CLI": ["AWS CLI", "AWS SAM CLI"],
    "AWS CloudWatch": ["AWS CloudWatch"],
    "AWS container orchestration (ECS, EKS)": ["AWS ECS", "AWS EKS", "container orchestration"],
    "AWS ECS": ["AWS ECS"],
    "AWS Glue and DynamoDB": ["AWS Glue", "AWS DynamoDB"],
    "AWS Glue, IAM, RDS": ["AWS Glue", "AWS IAM", "AWS RDS"],
    "AWS Lambda": ["AWS Lambda"],
    "AWS Lambda, API Gateway, CloudWatch, ECS, RDS": ["AWS Lambda", "AWS API Gateway", "AWS CloudWatch", "AWS ECS", "AWS RDS"],
    "AWS Lambda, DynamoDB, SQS, SDS, AWS CLI": ["AWS Lambda", "AWS DynamoDB", "AWS SQS", "AWS CLI"],
    "AWS QuickSight": ["AWS QuickSight"],
    "AWS RDS": ["AWS RDS"],
    "AWS serverless services (Lambda, Step Functions, EventBridge, SQS, SNS, API Gateway)": ["AWS Lambda", "AWS Step Functions", "AWS EventBridge", "AWS SQS", "AWS SNS", "AWS API Gateway"],
    "AWS serverless stack: Lambda, ECS, Fargate, SQS, Step Functions, CloudWatch, Kinesis, Glue": ["AWS Lambda", "AWS ECS", "AWS Fargate", "AWS SQS", "AWS Step Functions", "AWS CloudWatch", "AWS Kinesis", "AWS Glue"],
    "AWS Well Architected Framework": ["AWS Well-Architected Framework"],
    "Azure": ["Microsoft Azure"],
    "Azure, GCP": ["Microsoft Azure", "Google Cloud Platform"],
    "Bazel and build tool management at scale": ["Bazel", "build tooling at scale"],
    "C#": ["C#"],
    "C/C++": ["C", "C++"],
    "C2 systems, sensor fusion, autonomous systems": ["command and control (C2) systems", "sensor fusion", "autonomous systems"],
    "CAC, channel velocity and pipeline analytics": ["customer acquisition cost (CAC)", "channel velocity", "pipeline analytics"],
    "Cassandra": ["Apache Cassandra"],
    "Change data capture (CDC)": ["change data capture (CDC)"],
    "CircleCI": ["CircleCI"],
    "Clearing, settlements and treasury domain knowledge": ["clearing and settlements domain", "treasury domain"],
    "Client intake funnels and digital acquisition": ["client intake funnels", "digital acquisition"],
    "Cloud data warehouse (Google BigQuery)": ["Google BigQuery", "cloud data warehousing"],
    "Cloud-native architecture": ["cloud-native architecture"],
    "CMS data systems (IDRC, CCW, CDR)": ["CMS data systems"],
    "Concurrency": ["concurrency"],
    "Concurrency and fault-tolerance design in distributed systems": ["concurrency", "fault-tolerant design", "distributed systems"],
    "Confluence (documentation tool, named in Key Responsibilities)": ["Confluence"],
    "Consulting or services delivery under client SLAs": ["client services delivery under SLAs"],
    "Cross-functional stakeholder management and analytics roadmap prioritisation": ["stakeholder management", "roadmap prioritization"],
    "Cucumber and Gherkin BDD": ["Cucumber", "Gherkin", "behavior-driven development (BDD)"],
    "Data catalog management, retention policy and schema governance": ["data catalog management", "data retention policy", "schema governance"],
    "Data lakehouse and data mesh architectures": ["data lakehouse architecture", "data mesh architecture"],
    "Data structures and algorithms as a stated competency": ["data structures and algorithms"],
    "Data Vault": ["Data Vault modeling"],
    "Data visualization tools generally (Tableau or similar)": ["data visualization", "Tableau"],
    "Databricks": ["Databricks"],
    "Datadog or equivalent observability platform": ["Datadog", "observability tooling"],
    "dbt and transformation tooling": ["dbt", "data transformation tooling"],
    "dbt Cloud": ["dbt Cloud"],
    "dbt, Airflow or comparable orchestration": ["dbt", "Apache Airflow", "pipeline orchestration"],
    "dbt, Airflow or pipeline orchestration": ["dbt", "Apache Airflow", "pipeline orchestration"],
    "Deep AWS across compute, networking, IAM and data services": ["AWS compute services", "AWS networking", "AWS IAM"],
    "Defense, aerospace, robotics and safety-critical domains": ["defense domain", "aerospace domain", "robotics domain", "safety-critical systems"],
    "Delta Lake": ["Delta Lake"],
    "DevSecOps practices": ["DevSecOps"],
    "DHS Public Trust and TSA clearance eligibility": ["DHS Public Trust clearance", "TSA clearance"],
    "Digital health, telehealth or behavioural health domain, especially ABA therapy": ["digital health domain", "telehealth domain", "behavioral health domain", "ABA therapy domain"],
    "Dimensional modeling": ["dimensional modeling"],
    "Dimensional modeling and semantic layers": ["dimensional modeling", "semantic layer modeling"],
    "Disaster recovery and high-availability architecture": ["disaster recovery", "high-availability architecture"],
    "Distributed data-processing pipelines": ["distributed data processing"],
    "Distributed systems and service-oriented architecture": ["distributed systems", "service-oriented architecture (SOA)"],
    "ECS / EKS container orchestration": ["AWS ECS", "AWS EKS", "container orchestration"],
    "EdTech, higher education or student success domain": ["EdTech domain", "higher education domain", "student success domain"],
    "Elasticsearch": ["Elasticsearch"],
    "Elasticsearch cluster sustainment": ["Elasticsearch", "Elasticsearch cluster operations"],
    "Electronic court filing standards (ECF/EFM), Tyler Technologies": ["electronic court filing standards (ECF/EFM)", "Tyler Technologies"],
    "Embedded systems and real-time control": ["embedded systems", "real-time control systems"],
    "Engineering leadership of teams of 10+ (architect, engineering manager, technical director)": ["engineering leadership"],
    "Enterprise relational platforms (Teradata, Snowflake, DB2, Oracle, SQL Server)": ["Teradata", "Snowflake", "IBM DB2", "Oracle Database", "Microsoft SQL Server"],
    "Event-driven distributed architecture": ["event-driven architecture", "distributed systems"],
    "Experiment design and analysis": ["experimental design"],
    "FHIR, telehealth systems and healthcare APIs": ["FHIR", "telehealth systems", "healthcare APIs"],
    "Firewall protocols and network security": ["firewall configuration", "network security"],
    "Formal QA artefacts: test plans, test cases, defect tracking tooling": ["test plans", "test case design", "defect tracking"],
    "GCP": ["Google Cloud Platform"],
    "GitFlow": ["GitFlow"],
    "GitLab CI": ["GitLab CI/CD"],
    "GitLab CI/CD": ["GitLab CI/CD"],
    "Go": ["Go"],
    "Google Ads and Meta Ads conversion tracking": ["Google Ads", "Meta Ads", "conversion tracking"],
    "Google Analytics and Google Analytics 4": ["Google Analytics (GA4)"],
    "Google BigQuery": ["Google BigQuery"],
    "Google Tag Manager, tracking pixels and event tags": ["Google Tag Manager", "tracking pixels", "event tagging"],
    "Government cloud (AWS GovCloud, Azure Government)": ["AWS GovCloud", "Azure Government"],
    "Graph databases": ["graph databases"],
    "GraphQL": ["GraphQL"],
    "Growth engineering, marketing automation and RevOps tooling": ["growth engineering", "marketing automation", "RevOps tooling"],
    "gRPC": ["gRPC"],
    "Hadoop, HBase, Druid": ["Apache Hadoop", "Apache HBase", "Apache Druid"],
    "HAProxy load balancing": ["HAProxy", "load balancing"],
    "Healthcare data domain: CMS, claims, survey data, ICD-10, CPT, HCPCS": ["healthcare data domain", "claims data", "ICD-10", "CPT", "HCPCS", "CMS data systems"],
    "Healthcare domain": ["healthcare domain"],
    "High-load systems and large databases": ["high-load systems", "large-scale databases"],
    "HIPAA and patient-data privacy": ["HIPAA", "patient data privacy"],
    "Hiring and mentoring junior engineers": ["hiring", "mentoring engineers"],
    "HubSpot CRM, integration, field mapping and form building": ["HubSpot CRM", "CRM integration", "field mapping", "form building"],
    "Incident response as a practice": ["incident response"],
    "Informatica": ["Informatica"],
    "Infrastructure as code": ["infrastructure as code"],
    "Infrastructure-as-code and platform engineering": ["infrastructure as code", "platform engineering"],
    "Insurance and InsurTech domain": ["insurance domain", "InsurTech domain"],
    "Insurance domain (home, auto, commercial)": ["insurance domain"],
    "Insurance domain: home, auto and commercial lines. Recorded domains are banking and school spirit/athletics commerce.": ["insurance domain"],
    "ITU and FCC satellite regulations": ["ITU satellite regulations", "FCC satellite regulations"],
    "Jira": ["Jira"],
    "Jira and Confluence": ["Jira", "Confluence"],
    "JSON": ["JSON"],
    "JSON Web Tokens (JWT)": ["JSON Web Tokens (JWT)"],
    "Julia": ["Julia"],
    "JWT and token management": ["JSON Web Tokens (JWT)", "token management"],
    "Kafka and event-driven architecture": ["Apache Kafka", "event-driven architecture"],
    "Kibana": ["Kibana"],
    "KPI and OKR development, metrics standardization": ["KPI development", "OKR development", "metrics standardization"],
    "Kubernetes": ["Kubernetes"],
    "Kubernetes and Docker in production": ["Kubernetes", "Docker"],
    "Kubernetes, ArgoCD, StatefulSets": ["Kubernetes", "ArgoCD", "Kubernetes StatefulSets"],
    "Leading or mentoring a small team": ["team leadership", "mentoring engineers"],
    "Linux/Unix": ["Linux", "Unix"],
    "Looker": ["Looker"],
    "MariaDB": ["MariaDB"],
    "Marketing and acquisition analytics: channel attribution, marketing spend, audience segmentation, campaign performance": ["marketing analytics", "channel attribution", "marketing spend analysis", "audience segmentation", "campaign performance analysis"],
    "Measurement frameworks and metric definition": ["measurement frameworks", "metric definition"],
    "Medallion (bronze/silver/gold) architecture": ["medallion architecture"],
    "Mentoring and guiding developers": ["mentoring engineers"],
    "Mentoring and teaching coding best practices": ["mentoring engineers", "coding best practices"],
    "Mentoring less experienced engineers": ["mentoring engineers"],
    "Mentoring less-senior engineers": ["mentoring engineers"],
    "Mentorship and code review of engineers": ["mentoring engineers", "code review"],
    "Message queues (RabbitMQ, ZeroMQ, SQS, Event Bus)": ["message queues", "RabbitMQ", "ZeroMQ", "AWS SQS"],
    "Microservice deployment": ["microservices deployment"],
    "Microservice environments": ["microservices architecture"],
    "Microservices and cloud-native development": ["microservices architecture", "cloud-native architecture"],
    "Microservices architecture": ["microservices architecture"],
    "Microservices architecture and orchestration": ["microservices architecture", "service orchestration"],
    "Microsoft Azure": ["Microsoft Azure"],
    "Middleware architecture ownership": ["middleware architecture"],
    "Modern BI tooling (Sigma, Looker, Hex, Tableau)": ["BI tooling", "Sigma", "Looker", "Hex", "Tableau"],
    "Modern cloud warehouse (Snowflake, BigQuery, Databricks)": ["Snowflake", "Google BigQuery", "Databricks", "cloud data warehousing"],
    "Modern front-end build tools (Webpack, Vite)": ["Webpack", "Vite", "front-end build tooling"],
    "Modern REST microservice development": ["REST API development", "microservices architecture"],
    "Monitoring and observability tooling": ["monitoring", "observability tooling"],
    "Multi-tenant application architecture": ["multi-tenant architecture"],
    "Multi-tenant data lake": ["multi-tenant architecture", "data lake"],
    "Multi-touch attribution modelling": ["multi-touch attribution modeling"],
    "Next.js": ["Next.js"],
    "Node.js": ["Node.js"],
    "Node.js / TypeScript backend runtime": ["Node.js", "TypeScript"],
    "NodeJS": ["Node.js"],
    "NoSQL data stores": ["NoSQL databases"],
    "NoSQL databases": ["NoSQL databases"],
    "NoSQL databases and warehouses": ["NoSQL databases", "data warehousing"],
    "Observability": ["observability tooling"],
    "OCI (Open Container Initiative) image tooling": ["OCI image tooling"],
    "On-call operations rotation": ["on-call rotation"],
    "OpenShift": ["Red Hat OpenShift"],
    "Oracle": ["Oracle Database"],
    "Oracle BI Publisher": ["Oracle BI Publisher"],
    "Oracle Database": ["Oracle Database"],
    "Oracle E-Business Suite R12 (including ASCP)": ["Oracle E-Business Suite", "Oracle ASCP"],
    "Oracle Forms and Oracle Reports": ["Oracle Forms", "Oracle Reports"],
    "Oracle public APIs in program development": ["Oracle public APIs"],
    "Oracle Workflow": ["Oracle Workflow"],
    "Oracle, MS SQL Server, Sybase": ["Oracle Database", "Microsoft SQL Server", "Sybase"],
    "Orbit maneuvers and station-keeping": ["orbital maneuvers", "station-keeping"],
    "Orchestration tools: Airflow, Databricks Workflows": ["Apache Airflow", "Databricks Workflows", "pipeline orchestration"],
    "Parallel computing, CPU and memory behaviour": ["parallel computing", "CPU and memory profiling"],
    "Parallel programming as a QA/QC practice": ["parallel programming"],
    "Performance profiling": ["performance profiling"],
    "Pipeline observability: SLAs, SLOs, alerting tooling": ["pipeline observability", "SLA definition", "SLO definition", "alerting"],
    "PL/SQL": ["PL/SQL"],
    "Playwright": ["Playwright"],
    "Product analytics and user behaviour analysis": ["product analytics", "user behavior analysis"],
    "Production incident response and on-call": ["incident response", "on-call rotation"],
    "Production observability: structured logging, tracing, alerting": ["observability tooling", "structured logging", "distributed tracing", "alerting"],
    "Prometheus / Grafana": ["Prometheus", "Grafana"],
    "R, Perl": ["R", "Perl"],
    "Record linkage across file types": ["record linkage"],
    "Reporting dashboards and data visualization libraries": ["reporting dashboards", "data visualization"],
    "Rust": ["Rust"],
    "Salesforce, Apollo, Lusha and enrichment vendor platforms": ["Salesforce", "Apollo.io", "Lusha", "data enrichment platforms"],
    "Salesforce, Jira and Google Workspace as data sources": ["Salesforce", "Jira", "Google Workspace"],
    "SAS": ["SAS"],
    "Satellite subsystems (power, propulsion, communication, payload)": ["satellite subsystems"],
    "Secure coding / cybersecurity practice": ["secure coding", "cybersecurity practices"],
    "Secure coding practices": ["secure coding"],
    "Selenium": ["Selenium"],
    "Server provisioning": ["server provisioning"],
    "Service discovery": ["service discovery"],
    "Slack bot development and conversational interfaces": ["Slack bot development", "conversational interfaces"],
    "SLO definition": ["SLO definition"],
    "Snowflake and Amazon Redshift": ["Snowflake", "Amazon Redshift"],
    "SOAP web services": ["SOAP web services"],
    "SOC 2 and GDPR compliance groundwork": ["SOC 2 compliance", "GDPR compliance"],
    "SOC 2, data masking, encryption": ["SOC 2 compliance", "data masking", "encryption"],
    "Software networking": ["software networking"],
    "Spacecraft and ground station operations": ["spacecraft operations", "ground station operations"],
    "Spinnaker": ["Spinnaker"],
    "SRE practice": ["site reliability engineering (SRE)"],
    "SSL/TLS security protocols": ["SSL/TLS"],
    "SSO / SAML": ["single sign-on (SSO)", "SAML"],
    "Statsig or another experimentation platform": ["Statsig", "experimentation platforms"],
    "Stripe, usage-based billing, invoicing and subscriptions": ["Stripe", "usage-based billing", "invoicing", "subscription billing"],
    "Structured incident response, log analysis and post-incident reviews": ["incident response", "log analysis", "post-incident review"],
    "Supabase": ["Supabase"],
    "Swift, Kotlin, native iOS and Android": ["Swift", "Kotlin", "iOS development", "Android development"],
    "System testing with IT analysts": ["system testing"],
    "Tableau or Looker": ["Tableau", "Looker"],
    "Team leadership and mentoring of junior testers": ["team leadership", "mentoring engineers"],
    "Technical Design Documents (TDDs)": ["technical design documents"],
    "Technical design reviews and design documentation": ["technical design review", "technical documentation"],
    "Technical documentation as a named practice": ["technical documentation"],
    "Technical lead / architect role experience": ["technical leadership", "software architecture"],
    "Telemetry analysis": ["telemetry analysis"],
    "Terraform and Bicep (infrastructure as code)": ["Terraform", "Azure Bicep", "infrastructure as code"],
    "Terraform and infrastructure as code": ["Terraform", "infrastructure as code"],
    "Terraform and Terragrunt, infrastructure as code": ["Terraform", "Terragrunt", "infrastructure as code"],
    "Terraform or CloudFormation infrastructure automation": ["Terraform", "AWS CloudFormation", "infrastructure as code"],
    "Test automation framework design": ["test automation frameworks"],
    "Test automation or software testing certification": ["test automation", "software testing certification"],
    "Test planning and test case design": ["test planning", "test case design"],
    "Test progress monitoring and risk mitigation": ["test progress monitoring", "risk mitigation"],
    "Training and coaching stakeholders on BI tools and analytics practice": ["stakeholder training", "BI tooling"],
    "Translating wireframes and designs": ["wireframe-to-UI implementation"],
    "Two-sided marketplace analytics": ["marketplace analytics"],
    "Unity Catalog": ["Databricks Unity Catalog"],
    "Vagrant": ["Vagrant"],
    "Vercel": ["Vercel"],
    "Version control policy ownership": ["version control policy"],
    "Webflow": ["Webflow"],
    "XML": ["XML"],
    "XML and XSLT transformation": ["XML", "XSLT"],
}

# Atoms that denote the same skill under different wording. Key -> canonical atom.
# Applied after ATOMS, so the surviving name is the one on the right.
MERGE = {
    "test planning": "test plans",
    "test automation frameworks": "test automation",
    "architecture design review": "technical design review",
    "architecture documentation": "technical documentation",
    "health monitoring": "monitoring",
    "metrics standardization": "metric definition",
    "healthcare data domain": "healthcare domain",
    "telehealth systems": "telehealth domain",
    "InsurTech domain": "insurance domain",
    "parallel programming": "parallel computing",
    "technical leadership": "engineering leadership",
    "cloud data warehousing": "data warehousing",
}

# Programming languages excluded from the `other` list. SQL and its dialects stay,
# as do markup/data formats (JSON, XML, XSLT) and runtimes/frameworks (Node.js, Angular).
DROP_LANGUAGES = {
    "c", "c#", "c++", "go", "julia", "kotlin", "perl", "r", "rust", "swift", "typescript",
}
